name: Frontend Task
description: フロントエンドの実装におけるIssueを作成します
title: "[FE]: "
labels: ["frontend"]
assignees:
  - marromugi
body:
  - type: textarea
    id: story
    attributes:
      label: Story
      description: 作成するタスクの基になるストーリータスクのリンクを記載してください
      placeholder: "- https://github.com/username/repository/issues/1\n- https://github.com/username/repository/issues/2"
      render: Text
    validations:
      required: false
  - type: textarea
    id: related-issue
    attributes:
      label: 関連Issue
      description: 関連するIssueがあれば設定してください
      placeholder: "- https://github.com/username/repository/issues/1\n- https://github.com/username/repository/issues/2"
      render: Text
    validations:
      required: false
  - type: textarea
    id: detail
    attributes:
      label: 詳細
      description: タスクの詳細を記載してください
      placeholder: フォームのレイアウトを変更するタスクです
      value: "### タスク概要\n\n### 関連Issue\n"
    validations:
      required: false
  - type: textarea
    id: test
    attributes:
      label: テスト
      description: 実施すべきテスト項目があれば入力してください
      placeholder: "- [ ] ここにテスト内容を書く"
      value: "- [ ] ここにテスト内容を書く\n"
    validations:
      required: false
  - type: input
    id: figma
    attributes:
      label: Figma
      description: Figma のリンクを設定してください
      placeholder: "https://www.figma.com/file/xxxxxxxxxxxxxxxxxxxx"
    validations:
      required: true
